# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
#'node1' => {'memory' => '3048', 'cpus' => '4', 'ip' => '12', 'box' => 'rockylinux/8'},
#'almalinux-srv' => {'memory' => '1024', 'cpus' => '1', 'ip' => '12', 'box' => 'almalinux/8'},
#'debian-srv' => {'memory' => '1024', 'cpus' => '1', 'ip' => '13', 'box' => 'debian/bullseye64'},
'node' => {'memory' => '3048', 'cpus' => '2', 'ip' => '12', 'box' => 'ubuntu/focal64'},
#'node2' => {'memory' => '3048', 'cpus' => '4', 'ip' => '13', 'box' => 'ubuntu/focal64'},
}

Vagrant.configure('2') do |config|
  vms.each do |name, conf|
     config.vm.define "#{name}" do |my|
       my.vm.box = conf['box']
       my.vm.hostname = "#{name}"
       #my.vm.network 'private_network', ip: "192.168.33.#{conf['ip']}"
       my.vm.network 'public_network', ip: "192.168.3.#{conf['ip']}", bridge: "wlp3s0"
       my.vm.provision 'shell', path: "basic.sh"
       my.vm.provider 'virtualbox' do |vb|
          vb.memory = conf['memory']
          vb.cpus = conf['cpus']
       end
     end
  end
end